import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "coverage/**",
      // Generated by scripts/build-assets.mjs — lint the source it inlines.
      "src/player-asset.generated.ts",
    ],
  },
  js.configs.recommended,
  {
    // Node library source (src/html and src/react are browser code — below).
    files: ["src/**/*.ts"],
    ignores: ["src/html/**", "src/react/**"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Browser custom element: DOM + WebCodecs, typed against tsconfig.html.json.
    files: ["src/html/**/*.ts"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        project: "./tsconfig.html.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // React binding: DOM + WebCodecs + JSX, typed against tsconfig.react.json.
    files: ["src/react/**/*.{ts,tsx}"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        project: "./tsconfig.react.json",
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // Example servers: Node TS, linted without type info (not in tsconfig).
    files: ["examples/**/*.ts"],
    extends: [...tseslint.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // Node-only build helpers.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: globals.node,
    },
  },
  {
    // Page glue for the demo.
    files: ["examples/**/public/**/*.js"],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { sourceType: "module" },
    },
  },
  {
    files: ["**/*.mjs", "**/*.js"],
    ...tseslint.configs.disableTypeChecked,
  },
  prettier,
);
