/**
 * build-assets.mjs — inline the compiled browser element into the library.
 *
 * Reads dist/html (produced by `tsc -p tsconfig.html.json`) and emits
 * src/player-asset.generated.ts, which exports the <rtsp-player> script and
 * its source map as strings. serveRtspPlayer() serves those strings, so the
 * CJS and ESM builds ship identical bytes with no filesystem/path lookup.
 *
 * Generated file — never edit by hand; it is git-ignored and rebuilt here.
 */

import * as fs from "node:fs";
import * as path from "node:path";

const root = path.join(import.meta.dirname, "..");
const htmlDir = path.join(root, "dist", "html");
const outFile = path.join(root, "src", "player-asset.generated.ts");

const read = (name) => {
  try {
    return fs.readFileSync(path.join(htmlDir, name), "utf8");
  } catch {
    console.error(`[assets] missing dist/html/${name} — run build:html first`);
    process.exit(1);
  }
};

const js = read("rtsp-player.js");
const map = read("rtsp-player.js.map");

const out = `// AUTO-GENERATED by scripts/build-assets.mjs — do not edit.
// Inlines the compiled <rtsp-player> element so serveRtspPlayer() ships the
// same bytes from the CJS and ESM builds without any path lookup.
/* eslint-disable */
export const RTSP_PLAYER_JS: string = ${JSON.stringify(js)};
export const RTSP_PLAYER_JS_MAP: string = ${JSON.stringify(map)};
`;

fs.writeFileSync(outFile, out);
console.log(`[assets] wrote src/player-asset.generated.ts (${js.length} B js)`);
